using TagTool.Cache;
using TagTool.Common;
using TagTool.Serialization;
using System.Collections.Generic;

namespace TagTool.Tags.Definitions
{
    [TagStructure(Name = "multiplayer_variant_settings_interface_definition", Tag = "goof", Size = 0x10)]
    public class MultiplayerVariantSettingsInterfaceDefinition
    {
        public int Unknown;
        public List<GameEngineSetting> GameEngineSettings;

        [TagStructure(Size = 0x14)]
        public class GameEngineSetting
        {
            public StringId Name;
            public SettingCategoryValue SettingCategory;
            public List<Option> Options;

            public enum SettingCategoryValue : int
            {
                None,
                GlobalRespawnOptions,
                GlobalSocialOptions,
                GlobalMapOverrides,
                GlobalBaseTraitsMain,
                GlobalBaseTraitsHealth,
                GlobalBaseTraitsWeapons,
                GlobalBaseTraitsMovement,
                GlobalBaseTraitsSensors,
                GlobalBaseTraitsAppearance,
                Unknown,
                GlobalRespawnTraitsMain,
                GlobalRespawnTraitsHealth,
                GlobalRespawnTraitsWeapons,
                GlobalRespawnTraitsMovement,
                GlobalRespawnTraitsSensors,
                GlobalRespawnTraitsAppearance,
                Unknown2,
                GlobalPowerupsRedTraitsMain,
                GlobalPowerupsRedTraitsHealth,
                GlobalPowerupsRedTraitsWeapons,
                GlobalPowerupsRedTraitsMovement,
                GlobalPowerupsRedTraitsSensors,
                GlobalPowerupsRedTraitsAppearance,
                Unknown3,
                GlobalPowerupsBlueTraitsMain,
                GlobalPowerupsBlueTraitsHealth,
                GlobalPowerupsBlueTraitsWeapons,
                GlobalPowerupsBlueTraitsMovement,
                GlobalPowerupsBlueTraitsSensors,
                GlobalPowerupsBlueTraitsAppearance,
                Unknown4,
                GlobalPowerupsYellowTraitsMain,
                GlobalPowerupsYellowTraitsHealth,
                GlobalPowerupsYellowTraitsWeapons,
                GlobalPowerupsYellowTraitsMovement,
                GlobalPowerupsYellowTraitsSensors,
                GlobalPowerupsYellowTraitsAppearance,
                Unknown5,
                Unknown6,
                SlayerLeaderTraitsMain,
                SlayerLeaderTraitsHealth,
                SlayerLeaderTraitsWeapons,
                SlayerLeaderTraitsMovement,
                SlayerLeaderTraitsSensors,
                SlayerLeaderTraitsAppearance,
                Unknown7,
                OddballCarrierTraitsMain,
                OddballCarrierTraitsHealth,
                OddballCarrierTraitsWeapons,
                OddballCarrierTraitsMovement,
                OddballCarrierTraitsSensors,
                OddballCarrierTraitsAppearance,
                Unknown8,
                AssaultCarrierTraitsMain,
                AssaultCarrierTraitsHealth,
                AssaultCarrierTraitsWeapons,
                AssaultCarrierTraitsMovement,
                AssaultCarrierTraitsSensors,
                AssaultCarrierTraitsAppearance,
                Unknown9,
                CtfCarrierTraitsMain,
                CtfCarrierTraitsHealth,
                CtfCarrierTraitsWeapons,
                CtfCarrierTraitsMovement,
                CtfCarrierTraitsSensors,
                CtfCarrierTraitsAppearance,
                Unknown10,
                JuggernautJuggyTraitsMain,
                JuggernautJuggyTraitsHealth,
                JuggernautJuggyTraitsWeapons,
                JuggernautJuggyTraitsMovement,
                JuggernautJuggyTraitsSensors,
                JuggernautJuggyTraitsAppearance,
                Unknown11,
                KothHillTraitsMain,
                KothHillTraitsHealth,
                KothHillTraitsWeapons,
                KothHillTraitsMovement,
                KothHillTraitsSensors,
                KothHillTraitsAppearance,
                Unknown12,
                InfectionZombieTraitsMain,
                InfectionZombieTraitsHealth,
                InfectionZombieTraitsWeapons,
                InfectionZombieTraitsMovement,
                InfectionZombieTraitsSensors,
                InfectionZombieTraitsAppearance,
                Unknown13,
                InfectionAlphaZombieTraitsMain,
                InfectionAlphaZombieTraitsHealth,
                InfectionAlphaZombieTraitsWeapons,
                InfectionAlphaZombieTraitsMovement,
                InfectionAlphaZombieTraitsSensors,
                InfectionAlphaZombieTraitsAppearance,
                Unknown14,
                InfectionSafeHavenTraitsMain,
                InfectionSafeHavenTraitsHealth,
                InfectionSafeHavenTraitsWeapons,
                InfectionSafeHavenTraitsMovement,
                InfectionSafeHavenTraitsSensors,
                InfectionSafeHavenTraitsAppearance,
                Unknown15,
                InfectionLastManTraitsMain,
                InfectionLastManTraitsHealth,
                InfectionLastManTraitsWeapons,
                InfectionLastManTraitsMovement,
                InfectionLastManTraitsSensors,
                InfectionLastManTraitsAppearance,
                Unknown16,
                UnknownUnknownTraitsMain,
                UnknownUnknownTraitsHealth,
                UnknownUnknownTraitsWeapons,
                UnknownUnknownTraitsMovement,
                UnknownUnknownTraitsSensors,
                UnknownUnknownTraitsAppearance,
                Unknown17,
                TerritoriesDefenderTraitsMain,
                TerritoriesDefenderTraitsHealth,
                TerritoriesDefenderTraitsWeapons,
                TerritoriesDefenderTraitsMovement,
                TerritoriesDefenderTraitsSensors,
                TerritoriesDefenderTraitsAppearance,
                Unknown18,
                TerritoriesAttackerTraitsMain,
                TerritoriesAttackerTraitsHealth,
                TerritoriesAttackerTraitsWeapons,
                TerritoriesAttackerTraitsMovement,
                TerritoriesAttackerTraitsSensors,
                TerritoriesAttackerTraitsAppearance,
                Unknown19,
                VipTeamTraitsMain,
                VipTeamTraitsHealth,
                VipTeamTraitsWeapons,
                VipTeamTraitsMovement,
                VipTeamTraitsSensors,
                VipTeamTraitsAppearance,
                Unknown20,
                VipInfluenceTraitsMain,
                VipInfluenceTraitsHealth,
                VipInfluenceTraitsWeapons,
                VipInfluenceTraitsMovement,
                VipInfluenceTraitsSensors,
                VipInfluenceTraitsAppearance,
                Unknown21,
                VipVipTraitsMain,
                VipVipTraitsHealth,
                VipVipTraitsWeapons,
                VipVipTraitsMovement,
                VipVipTraitsSensors,
                VipVipTraitsAppearance,
                Unknown22,
                EditorEditorTraitsMain,
                EditorEditorTraitsHealth,
                EditorEditorTraitsWeapons,
                EditorEditorTraitsMovement,
                EditorEditorTraitsSensors,
                EditorEditorTraitsAppearance,
                Unknown23,
                CtfTop,
                SlayerTop,
                OddballTop,
                KothTop,
                EditorTop,
                JuggernautTop,
                TerritoriesTop,
                AssaultTop,
                InfectionTop,
                VipTop,
                Unknown24,
                GlobalPowerups,
                GlobalRespawnAdvanced,
                GlobalRespawnModifiers,
                SlayerMain,
                Unknown25,
                SlayerScoring,
                OddballMain,
                OddballScoring,
                AssaultMain,
                AssaultScoring,
                CtfMain,
                CtfScoring,
                JuggernautMain,
                JuggernautScoring,
                KothMain,
                KothScoring,
                InfectionMain,
                InfectionAdvanced,
                InfectionScoring,
                Unknown26,
                Unknown27,
                Unknown28,
                Unknown29,
                Unknown30,
                Unknown31,
                Unknown32,
                Unknown33,
                Unknown34,
                Unknown35,
                Unknown36,
                Unknown37,
                VipMain,
                VipScoring,
                TerritoriesMain,
                TerritoriesScoring,
                TemplatesTraitsMain,
                TemplatesTraitsHealth,
                TemplatesTraitsWeapons,
                TemplatesTraitsMovement,
                TemplatesTraitsSensors,
                TemplatesTraitsAppearance,
                TemplatesDynamicTraitsMain,
                TemplatesDynamicTraitsHealth,
                TemplatesDynamicTraitsWeapons,
                TemplatesDynamicTraitsMovement,
                TemplatesDynamicTraitsSensors,
                TemplatesDynamicTraitsAppearance,
            }

            [TagStructure(Size = 0x3C)]
            public class Option
            {
                public CachedTagInstance ExplicitSubmenu;
                public CachedTagInstance TemplateBasedSubmenu;
                public SettingCategoryValue SubmenuSettingCategory;
                public StringId SubmenuName;
                public StringId SubmenuDescription;
                public CachedTagInstance ValuePairs;
            }
        }
    }
}