using TagTool.Cache;
using TagTool.Common;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using static TagTool.Tags.TagFieldFlags;

namespace TagTool.Tags.Definitions.Gen4
{
    [TagStructure(Name = "multiplayer_variant_settings_interface_definition", Tag = "goof", Size = 0x10)]
    public class MultiplayerVariantSettingsInterfaceDefinition : TagStructure
    {
        public StringId Name;
        public List<VariantSettingEditReferenceBlock> GameEngineSettings;
        
        [TagStructure(Size = 0x14)]
        public class VariantSettingEditReferenceBlock : TagStructure
        {
            public StringId Name;
            public GameEngineSettings SettingCategory;
            public List<VariantOptionBlock> Options;
            
            public enum GameEngineSettings : int
            {
                GameBaseMisc,
                GameBaseRespawn,
                GameBaseSocial,
                GameBaseMap,
                GameBasePrototype,
                PowerupDuration,
                CtfTopLevelOptions,
                SlayerTopLevelOptions,
                OddballTopLevelOptions,
                KingTopLevelOptions,
                SandboxTopLevelOptions,
                SandboxInForgeOptions,
                JuggernautTopLevelOptions,
                TerritoriesTopLevelOptions,
                AssaultTopLevelOptions,
                InfectionTopLevelOptions,
                VipTopLevelOptions,
                TrainingTopLevelOptions,
                MoshTopLevelOptions,
                CustomTopLevelOptions,
                MapOverrideAdvancedOptions,
                RespawnAdvancedOptions,
                RespawnModifiers,
                SlayerPrimaryOptions,
                SlayerAdvancedOptions,
                SlayerScoringOptions,
                OddballPrimaryOptions,
                OddballAdvancedOptions,
                AssaultPrimaryOptions,
                AssaultAdvancedOptions,
                CtfPrimaryOptions,
                CtfAdvancedOptions,
                JuggernautPrimaryOptions,
                JuggernautAdvancedOptions,
                KingPrimaryOptions,
                KingAdvancedOptions,
                InfectionPrimaryOptions,
                InfectionAdvancedOptions,
                InfectionScoringOptions,
                TargetTrainingPrimaryOptions,
                TrainingAdvancedOptions,
                Target1Setup,
                Target2Setup,
                Target3Setup,
                Target4Setup,
                Target5Setup,
                Target6Setup,
                Target7Setup,
                Target8Setup,
                Target9Setup,
                Target10Setup,
                VipPrimaryOptions,
                VipAdvancedOptions,
                TerritoriesPrimaryOptions,
                TerritoriesAdvancedOptions,
                AiTemplateTraits,
                CampaignTopLevelOptions,
                SurvivalTopLevelOptions,
                FirefightTopLevelOptions,
                MegaloOptionsSubmenuTrigger,
                SurvivalPrimaryOptions,
                SurvivalScenarioSettingsOptions,
                SurvivalSetOptions,
                SurvivalRoundOptions,
                SurvivalRound0CategoryOptions,
                SurvivalRound0SkullsCategoryOptions,
                SurvivalRound0InitialWaveOptions,
                SurvivalRound0PrimaryWaveOptions,
                SurvivalRound0BossWaveOptions,
                SurvivalRound1CategoryOptions,
                SurvivalRound1SkullsCategoryOptions,
                SurvivalRound1InitialWaveOptions,
                SurvivalRound1PrimaryWaveOptions,
                SurvivalRound1BossWaveOptions,
                SurvivalRound2CategoryOptions,
                SurvivalRound2SkullsCategoryOptions,
                SurvivalRound2InitialWaveOptions,
                SurvivalRound2PrimaryWaveOptions,
                SurvivalRound2BossWaveOptions,
                SurvivalRoundTemplateCategoryOptions,
                SurvivalRoundTemplateSkullsCategoryOptions,
                SurvivalRoundTemplateInitialWaveOptions,
                SurvivalRoundTemplatePrimaryWaveOptions,
                SurvivalRoundTemplateBossWaveOptions,
                SurvivalBonusWaveSkullsCategoryOptions,
                SurvivalBonusWaveOptions,
                SurvivalSpartanOptions,
                SurvivalEliteOptions,
                SurvivalAiTraitsTraits,
                SurvivalAiTraitsTemplated,
                SurvivalLivesOptions,
                SurvivalLoadoutOptions,
                SurvivalObjectiveOptions,
                SurvivalCustomSkullOptions,
                CustomSkullRedOptions,
                CustomSkullYellowOptions,
                CustomSkullBlueOptions,
                RedSkullAiTraitsTraits,
                RedSkullAiTraitsTemplated,
                YellowSkullAiTraitsTraits,
                YellowSkullAiTraitsTemplated,
                BlueSkullAiTraitsTraits,
                BlueSkullAiTraitsTemplated,
                SpartanLoadouts,
                SpartanLoadoutsTier1,
                SpartanLoadoutsTier1Loadout0,
                SpartanLoadoutsTier1Loadout1,
                SpartanLoadoutsTier1Loadout2,
                SpartanLoadoutsTier1Loadout3,
                SpartanLoadoutsTier1Loadout4,
                SpartanLoadoutsTier2,
                SpartanLoadoutsTier2Loadout0,
                SpartanLoadoutsTier2Loadout1,
                SpartanLoadoutsTier2Loadout2,
                SpartanLoadoutsTier2Loadout3,
                SpartanLoadoutsTier2Loadout4,
                SpartanLoadoutsTier3,
                SpartanLoadoutsTier3Loadout0,
                SpartanLoadoutsTier3Loadout1,
                SpartanLoadoutsTier3Loadout2,
                SpartanLoadoutsTier3Loadout3,
                SpartanLoadoutsTier3Loadout4,
                EliteLoadouts,
                EliteLoadoutsTier1,
                EliteLoadoutsTier1Loadout0,
                EliteLoadoutsTier1Loadout1,
                EliteLoadoutsTier1Loadout2,
                EliteLoadoutsTier1Loadout3,
                EliteLoadoutsTier1Loadout4,
                EliteLoadoutsTier2,
                EliteLoadoutsTier2Loadout0,
                EliteLoadoutsTier2Loadout1,
                EliteLoadoutsTier2Loadout2,
                EliteLoadoutsTier2Loadout3,
                EliteLoadoutsTier2Loadout4,
                EliteLoadoutsTier3,
                EliteLoadoutsTier3Loadout0,
                EliteLoadoutsTier3Loadout1,
                EliteLoadoutsTier3Loadout2,
                EliteLoadoutsTier3Loadout3,
                EliteLoadoutsTier3Loadout4,
                InfinitySettings,
                Ordnance,
                PersonalOrdnance,
                PersonalOrdnanceLeftBank,
                PersonalOrdnanceMiddleBank,
                PersonalOrdnanceRightBank,
                RedPowerup,
                YellowPowerup,
                BluePowerup,
                Traits,
                KillRewards,
                PlayerTraitsBasePlayer,
                PlayerTraitsRespawn,
                PlayerTraitsRedPowerupPrimary,
                PlayerTraitsBluePowerupPrimary,
                PlayerTraitsYellowPowerupPrimary,
                PlayerTraitsCustomPowerupPrimary,
                PlayerTraitsSurvivalSpartanPlayer,
                PlayerTraitsSurvivalElitePlayer,
                PlayerTraitsEliteRespawn,
                PlayerTraitsRedSkullSpartan,
                PlayerTraitsRedSkullElite,
                PlayerTraitsYellowSkullSpartan,
                PlayerTraitsYellowSkullElite,
                PlayerTraitsBlueSkullSpartan,
                PlayerTraitsBlueSkullElite,
                PlayerTraitsSandboxEditor,
                PlayerTraitsMegaloCustom1,
                PlayerTraitsMegaloCustom2,
                PlayerTraitsMegaloCustom3,
                PlayerTraitsMegaloCustom4,
                PlayerTraitsMegaloCustomDynamic1,
                PlayerTraitsMegaloCustomDynamic2,
                PlayerTraitsMegaloCustomDynamic3,
                PlayerTraitsMegaloCustomDynamic4,
                PlayerTraitsRedPowerupSecondary,
                PlayerTraitsBluePowerupSecondary,
                PlayerTraitsYellowPowerupSecondary,
                PlayerTraitsCustomPowerupSecondary,
                TraitZoneAlphaPlayerTraits,
                TraitZoneBravoPlayerTraits,
                TraitZoneCharliePlayerTraits,
                TraitZoneDeltaPlayerTraits,
                PlayerTemplateTraits,
                PlayerTemplateTraitsShields,
                PlayerTemplateTraitsWeapons,
                PlayerTemplateTraitsMovement,
                PlayerTemplateTraitsSensors,
                PlayerTemplateTraitsAppearance,
                PlayerTemplateTraitsAbilities,
                EditorTemplateTraits,
                EditorTemplateTraitsShields,
                EditorTemplateTraitsWeapons,
                EditorTemplateTraitsMovement,
                EditorTemplateTraitsSensors,
                EditorTemplateTraitsAppearance,
                EditorTemplateTraitsAbilities,
                RunTimeTemplateTraits,
                RunTimeTemplateTraitsShields,
                RunTimeTemplateTraitsWeapons,
                RunTimeTemplateTraitsMovement,
                RunTimeTemplateTraitsSensors,
                RunTimeTemplateTraitsAppearance,
                RunTimeTemplateTraitsAbilities
            }
            
            [TagStructure(Size = 0x3C)]
            public class VariantOptionBlock : TagStructure
            {
                [TagField(ValidTags = new [] { "goof" })]
                public CachedTag SubCategory;
                [TagField(ValidTags = new [] { "goof" })]
                public CachedTag PlayerTraitUi;
                public GameEngineSettings PlayerTraitCategory;
                public StringId CategoryName;
                public StringId CategoryDescription;
                [TagField(ValidTags = new [] { "sily" })]
                public CachedTag ValuePairs;
            }
        }
    }
}
